# Disease Diagnose

Nosso trabalho consiste em auxiliar o médico na hora de diagnosticar seus
pacientes.  
Através de um banco de dados, que será alimentado, nosso sistema irá indicar
probabilidades de diagnósticos, ou seja, qual doença é mais possível que o paciente tenha
contraído.  
Após a análise o médico poderá avaliar, ou pedir um exame, para confirmar o
diagnóstico. Caso essa avaliação não confirme a doença com mais probabilidade o médico
poderá alimentar o sistema com essa informação e permitir com que as probabilidades
sejam recalculadas a partir daquela informação.

## Modelo Conceitual

<img src="bd-trabalho-etapa1-uml-2.jpg">

## Criação das tabelas

In [ ]:
%defaultDatasource jdbc:h2:mem:db

In [ ]:
CREATE TABLE Paciente (
  ID VARCHAR(9) NOT NULL,
  nome VARCHAR(50),
  nascimento VARCHAR(10),
  celular VARCHAR(7),
  localidade VARCHAR(9),
  PRIMARY KEY(ID)
) AS SELECT
    ID,
    nome,
    nascimento,
    celular, 
    localidade
FROM CSVREAD('../data/Paciente.csv');

CREATE TABLE Doenca (
  codigo VARCHAR(8) NOT NULL,
  nome VARCHAR(50),
  PRIMARY KEY(codigo)
) AS SELECT
    codigo,
    nome
FROM CSVREAD('../data/Doenca.csv');

CREATE TABLE Sintomas (
  codigo VARCHAR(8) NOT NULL,
  nome VARCHAR(50),
  PRIMARY KEY(codigo)
) AS SELECT
    codigo,
    nome
FROM CSVREAD('../data/Sintomas.csv');

CREATE TABLE Diagnostico (
  ID VARCHAR(10) NOT NULL,
  doencaCodigo VARCHAR(8),
  data VARCHAR(10),
  PRIMARY KEY(ID)
) AS SELECT
    ID,
    doencaCodigo,
    data
FROM CSVREAD('../data/Diagnostico.csv');

CREATE TABLE DoencaSintomas (
  doencaCodigo VARCHAR(8) NOT NULL,
  sintomaCodigo VARCHAR(8) NOT NULL,
  FOREIGN KEY(doencaCodigo)
    REFERENCES Doenca(codigo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(sintomaCodigo)
    REFERENCES Sintomas(codigo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
) AS SELECT
    doencaCodigo,
    sintomaCodigo
FROM CSVREAD('../data/DoencaSintomas.csv');

CREATE TABLE PacienteDiagnostico (
  pacienteID VARCHAR(9) NOT NULL,
  diagnosticoID VARCHAR(10) NOT NULL,
  FOREIGN KEY(pacienteID)
    REFERENCES Paciente(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(diagnosticoID)
    REFERENCES Diagnostico(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
) AS SELECT
    pacienteID,
    diagnosticoID
FROM CSVREAD('../data/PacienteDiagnostico.csv');

CREATE TABLE PacienteSintomas (
  pacienteID VARCHAR(9) NOT NULL,
  sintomaCodigo VARCHAR(8) NOT NULL,
  FOREIGN KEY(pacienteID)
    REFERENCES Paciente(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(sintomaCodigo)
    REFERENCES Sintomas(codigo)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
) AS SELECT
    pacienteID,
    sintomaCodigo
FROM CSVREAD('../data/PacienteSintomas.csv');

CREATE TABLE Educacao (
  D_code VARCHAR(8) NOT NULL,
  Educacao VARCHAR(30),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Educação, 
    Prob
FROM CSVREAD('../data/Educacao.csv');

CREATE TABLE Emprego (
  D_code VARCHAR(8) NOT NULL,
  Educacao VARCHAR(30),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Emprego, 
    Prob
FROM CSVREAD('../data/Emprego.csv');

CREATE TABLE Idade (
  D_code VARCHAR(8) NOT NULL,
  Educacao VARCHAR(30),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Idade, 
    Prob
FROM CSVREAD('../data/Idade.csv');

CREATE TABLE Raca (
  D_code VARCHAR(8) NOT NULL,
  Raca VARCHAR(30),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Raça, 
    Prob
FROM CSVREAD('../data/Raca.csv');

CREATE TABLE Regiao (
  D_code VARCHAR(8) NOT NULL,
  Regiao VARCHAR(30),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Região, 
    Prob
FROM CSVREAD('../data/Regiao.csv');

CREATE TABLE Renda (
  D_code VARCHAR(8) NOT NULL,
  Renda VARCHAR(30),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Renda, 
    Prob
FROM CSVREAD('../data/Renda.csv');

CREATE TABLE Sexo (
  D_code VARCHAR(8) NOT NULL,
  Sexo VARCHAR(1),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Sexo, 
    Prob
FROM CSVREAD('../data/Sexo.csv');

CREATE TABLE Status (
  D_code VARCHAR(8) NOT NULL,
  Status VARCHAR(1),
  Prob FLOAT(4,2)
  PRIMARY KEY(D_codigo)
) AS SELECT
    D_codigo,
    Status, 
    Prob
FROM CSVREAD('../data/Status.csv');

## Queries

In [ ]:
SELECT * FROM Paciente WHERE Paciente.nascimento LIKE '%1990'